### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ajgagnon** [FoundryApp/foundry-cli#6]
Was looking forward to giving this service a go. However, I'm getting timeout issues so I can't get started:

![image](https://user-images.githubusercontent.com/2569725/90810722-0ce7da00-e2e9-11ea-854b-d42023ff5cb3.png)

**Comment by mlejva** [comment]
Hi @ajgagnon and thank you for the interest. However, we had to shutdown Foundry because we weren't able to attract enough users.
